import React, { useEffect, useState } from 'react'
import { useSelector, useDispatch } from 'react-redux'
import { makeSelectUserAccounts } from '../redux/selector/userAccounts'
import { getAccounts } from '../redux/actions/userAccountsAction'

import type { NextPage } from 'next'
import Head from 'next/head'

import Grid from '@material-ui/core/Grid'

import Loading from '../components/loading/loading'
import AccountDataLists from '../components/accounts/accountTableLists'
const Home: NextPage = () => {
  const dispatch = useDispatch()
  const { loading, accounts } = useSelector(makeSelectUserAccounts)
  useEffect(() => {
    console.log(accounts.length <= 0)
    if (accounts.length <= 0) {
      dispatch(getAccounts())
    }
  }, [])

  return (
    <div>
      <Head>
        <title>Consequence World</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {loading ? (
          <div className="loading-container">
            <Loading />
          </div>
        ) : (
          <Grid container justifyContent="center" alignItems="center">
            <Grid className="container" item sm={12}>
              <AccountDataLists accounts={accounts} />
            </Grid>
          </Grid>
        )}
      </main>
    </div>
  )
}

export default Home
